### ISSUE TITLE
Hiking at Thatcher Woods

### ISSUE THREAD

**Issue by jim-z** [fpdcc/webmap_data_updates#96]
poi info id=232

change hiking to =1

**Comment by versatilehuman** [comment]
We had previously only been applying hiking to locations with recognized trails. So we should probably talk about this more. 

I think Thatcher is fine to list as hiking because it has popular, well established trails and we are considering formalizing. But we should hold off on others until we have better criteria for what sites support hiking.

@glw please also change dogs_leash --> 1 here

**Comment by glw** [comment]
dog_leash = 1 - Done.

**Comment by versatilehuman** [comment]
Now irrelevant with trails on the map
